### ISSUE TITLE
Clan settings (and the additional features they bring)

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace-Minecraft-Mods/Clans#114]
Allow clans to have settings within their clan. This should be a dynamic system similar to how permissions systems work: a group can be given a permission/setting, and all higher groups also get it, and certain players can be included/excluded from these permissions. Most permissions are boolean values, true/false, but other types may be permitted as needed, like for rent amount. Some of these permissions should be:
- [x] Can invite players
- [x] Can claim/unclaim/setbanner/sethome/etc
- [ ] Can revoke invites (#109)
- [ ] How many claims each player can make
- [ ] How many outposts a player can make (#91)
- [ ] Can abandon land claimed by self in the clan
- [ ] Can abandon land claimed by others in the clan
- [ ] Can issue private plots (#4)
- [ ] Can revoke private plots (#4)
- [x] Can lock chests privately (#34)
- [x] Can lock chests publicly (#34)
- [x] Can lock chests protectedly (#34)
- [x] Can bypass/override locks (#34)
- [ ] Rent amount (replaces /clan setrent)
- [ ] Emergency funds source (clan can draw from these players instead of disbanding)
- [x] Access (containers, doors/levers/other interaction, animal killing, mob killing, block placement, block break). This option should allow all of these by default for clan members, and be able to be configured for non-members as well.
- [x] Who can PVP when on claims

Feel free to suggest more and I will edit them into the list

**Comment by kreezxil** [comment]
Does this exist in the mod yet? If not which permission system do you recommend? I was thinking of going with Forge Essentials as it also supports World Edit style features.

**Comment by The-Fireplace** [comment]
This part isn't related to a permission system, it just behaves similar to one but within a clan. So for example, I can grant specific players (or anyone) access to interact with things on my clan's land. As for my recommended permission system, I find LuckPerms really convenient, the web editor for it works wonderfully.

**Comment by The-Fireplace** [comment]
And the checked parts exist in my 1.4 development branch, which I'm still working some of the bugs out of before I push something out to patreon.

**Comment by kreezxil** [comment]
I was looking for a pure forge alternative

**Comment by kreezxil** [comment]
I guess i'm still going to use FTB UTILITIES for the perms then, i'm familiar with it.

**Comment by The-Fireplace** [comment]
The initial feature and some basic settings are added. Keeping this open and pushing the milestone because I don't expect to get all of these settings added in this version.
